sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.3
before_install: gem install bundler -v 2.0.1
deploy:
  provider: rubygems
  api_key:
    secure: EeoAjhLUodzU6JQEjkwb5VrItqztFNe8UINerGX0+pw6sDo/BLKQyIn5qQauc+lsuu4vn1/AOlAV+zVRmsBfPGM7QB7FbVHiv+Ru21MZ189evc94T43cjnP4AQzza8Y/30Avqz/IM7PIXM24fMmMdYApyYtW/itHXJoZC6202sPO71yQ95X8YzKfGPAqCGiYpLQzZXHPk9gRVn2LC+DALz/ARMPTMd3gf7F5pPdpto4h0vMhAV52HJxXB3RShi9cbQ2unRmTKTWblQJ3N7BJqZspcl7OA8FdzT5v8bnJulRi4uXCm54Rh0VCZqBryhgdZFdrYFKPv162R4JwY/Q9ug0gGJ3ZvApYKZxubbYAYUBIc9JZza2FmPGrb1f4y21i2JGObpx9+BSOk7TbFIDn3dsQPRplGma+E6/DD5q51dYK56bCdI2FKLF3ImvqqkeFF3tP3L/i0rxj2IhETcuYF7Aoc2rInMKj+zdMAxTFnuO/y8K2kZSw7VPrN/fX1ZbV4pzjxRY+8jUYPCqXkVX3UD0IWtFbfaNKrpxDJNcGO/OZFx2TR/llz8v4H04TIREerKkcCv73QhpceXzB7VzF0e8ADsBDtO8WbsNO4/Qbyxi+S9r9c6ppS/TX3USGMXUVGn0t4cX24Wzvdkp8ntVM5LvkSQKu0BbIJ+MI3PbwoXg=
  gem: yanapiri
  on:
    tags: true
    repo: faloi/yanapiri
